Fixed 'for all' installations failing if one or more users don't have Steam installed Those users will now be skipped instead

diff --git a/sssm b/sssm
--- a/sssm
+++ b/sssm
@@ -5,15 +5,16 @@
 # This script can install, upgrade and remove steam skins for specific users.
 
 # Constants
-C_GREEN='\033[1;32m'
+C_ORANGE='\033[0;33m'
 C_RED='\033[1;31m'
+C_GREEN='\033[1;32m'
 C_BLUE='\033[1;34m'
 C_YELLOW='\033[1;33m'
 C_NC='\033[0m'
 SSSM_VERSION="1.1.1"
 
 # Parameters
-action=$1
+action="$1"
 
 # Functions
 function usage()
@@ -43,11 +44,13 @@ function usage()
     echo "                           If left empty, uninstall for all users."
     echo -e "  - ${C_BLUE}version${C_NC}"
     echo "      Prints the manager's version and exits."
+    exit 1
 }
 
 function version()
 {
     echo "Simple Steam Skin Manager v${SSSM_VERSION}"
+    return 0
 }
 
 function list()
@@ -77,6 +80,7 @@ function list()
             fi
         done
     fi
+    return 0
 }
 
 function sync()
@@ -89,14 +93,13 @@ function sync()
     if [ -z "$skin" ]
     then
         usage
-        exit 1
     fi
 
     # if 'user' is empty, install for all users
     if [ -z "$user" ]
     then
         sync_forall "$skin"
-        exit $?
+        return $?
     fi
 
     echo -e "${C_BLUE} => ${C_NC}Installing skin ${C_GREEN}${skin}${C_NC} for user ${C_GREEN}${user}${C_NC}."
@@ -105,14 +108,14 @@ function sync()
     if [ ! -d "/usr/share/steam/skins/${skin}" ]
     then
         echo -e "${C_BLUE} => ${C_RED}Installation failed:${C_NC} Skin ${C_GREEN}${skin}${C_NC} could not be found in /usr/share/steam/skins."
-        exit 1
+        exit 2
     fi
 
     # Check to make sure the user actually has Steam installed
     if [ ! -d "/home/${user}/.local/share/Steam" ]
     then
-        echo -e "${C_BLUE} => ${C_RED}Installation failed:${C_NC} User ${C_GREEN}${user}${C_NC} does not seem to have Steam installed."
-        exit 1
+        echo -e "${C_BLUE} => ${C_ORANGE}Installation skipped:${C_NC} User ${C_GREEN}${user}${C_NC} does not seem to have Steam installed."
+        return 1
     fi
 
     # Create the directory, nuke the skin if it already exists and copy the new skin over
@@ -130,8 +133,9 @@ function sync()
         echo -e "${C_BLUE} => ${C_NC}Installation completed successfully."
     else
         echo -e "${C_BLUE} => ${C_RED}Installation failed:${C_NC} Error while copying or setting ownership."
-        exit 1
+        exit 2
     fi
+    return 0
 }
 
 function sync_forall()
@@ -148,13 +152,17 @@ function sync_forall()
         if [ "$user" != "lost+found" ] && [ "$user" != "root" ]
         then
             sync "$skin" "$user"
-            if [ $? -ne 0 ]
+
+            # 0 means success, 1 means skipped, > 1 means failed
+            res=$?
+            if [ $res -gt 1 ]
             then
-                exit 1
+                exit $res
             fi
         fi
     done
     echo -e "${C_BLUE}=> ${C_NC}Installation completed successfully for all users."
+    return 0
 }
 
 function remove()
@@ -167,14 +175,13 @@ function remove()
     if [ -z "$skin" ]
     then
         usage
-        exit 1
     fi
 
     # if 'user' is empty, uninstall for all users
     if [ -z "$user" ]
     then
         remove_forall "$skin"
-        exit $?
+        return $?
     fi
 
     echo -e "${C_BLUE} => ${C_NC}Uninstalling skin ${C_GREEN}${skin}${C_NC} for user ${C_GREEN}${user}${C_NC}."
@@ -182,8 +189,8 @@ function remove()
     # Check to make sure the user actually has Steam installed
     if [ ! -d "/home/${user}/.local/share/Steam" ]
     then
-        echo -e "${C_BLUE} => ${C_RED}Uninstallation failed:${C_NC} User ${C_GREEN}${user}${C_NC} does not seem to have Steam installed."
-        exit 1
+        echo -e "${C_BLUE} => ${C_ORANGE}Uninstallation skipped:${C_NC} User ${C_GREEN}${user}${C_NC} does not seem to have Steam installed."
+        return 1
     fi
 
     # Check if the skin is installed and, if so, remove it
@@ -193,18 +200,20 @@ function remove()
         rm -rf "${SKINDIR}/${skin}"
 
         # Check if the uninstallation succeeded
-        if [ $? -eq 0 ]
+        res=$?
+        if [ $res -eq 0 ]
         then
             echo -e "${C_BLUE} => ${C_NC}Uninstallation completed successfully."
         else
             echo -e "${C_BLUE} => ${C_RED}Uninstallation failed:${C_NC} Error while removing files."
-            exit 1
+            exit $res
         fi
 
     else
-        echo -e "${C_BLUE} => ${C_RED}Uninstallation failed:${C_NC} User ${C_GREEN}${user}${C_NC} does not seem to have the skin ${C_GREEN}${skin}${C_NC} installed."
-        exit 1
+        echo -e "${C_BLUE} => ${C_ORANGE}Uninstallation skipped:${C_NC} User ${C_GREEN}${user}${C_NC} does not seem to have the skin ${C_GREEN}${skin}${C_NC} installed."
+        return 1
     fi
+    return 0
 }
 
 function remove_forall()
@@ -221,13 +230,17 @@ function remove_forall()
         if [ "$user" != "lost+found" ] && [ "$user" != "root" ]
         then
             remove "$skin" "$user"
-            if [ $? -ne 0 ]
+
+            # 0 means success, 1 means skipped, > 1 means failed
+            res=$?
+            if [ $res -gt 1 ]
             then
-                exit 1
+                exit $res
             fi
         fi
     done
     echo -e "${C_BLUE}=> ${C_NC}Uninstallation completed successfully for all users."
+    return 0
 }
 
 # Main Script
@@ -247,5 +260,6 @@ case "$action" in
         ;;
     *)
         usage
-        exit 1
+        ;;
 esac
+exit $?
